./exp-results/training-09x09-0127-on-0127.png: ./exp-results/2017_10_19_14_28_16-test_3D_4actions_blind-none_0001_local/videos/99988800.mp4 #py/process.py
	python py/process.py video_to_snapshot $< $@

./exp-results/training-1000-on-0127.png: ./exp-results/2017_10_19_17_34_49-test_3D_4actions_blind-none_0001_local/videos/99968400.mp4 #py/process.py
	python py/process.py video_to_snapshot $< $@

./exp-results/training-1000_on_square_map.png: ./exp-results/planning-09x09-0002/videos/gen_stats_latest_loaded-from-training-1000_acting-on-planning-09x09-0002_vars-True_apples-0.mp4 #py/process.py
	python py/process.py square_map_video_to_snapshot $< $@

./exp-results/training-1000_on_wrench_map.png: ./exp-results/planning-09x09-0004/videos/gen_stats_latest_loaded-from-training-1000_acting-on-planning-09x09-0004_vars-True_apples-0.mp4 #py/process.py
	python py/process.py wrench_map_video_to_snapshot $< $@

./exp-results/training-1000_on_goal_map.png: ./exp-results/planning-09x09-0006/videos/gen_stats_latest_loaded-from-training-1000_acting-on-planning-09x09-0006_vars-True_apples-0.mp4 #py/process.py
	python py/process.py goal_map_video_to_snapshot $< $@

map_snapshot_fname=./exp-results/training-09x09-$(1).png
.PHONY:
make_snapshot_png_all: $(foreach mapid,0127 0169 0246 0336 0445 0589 0691 0828 0844 0956, $(call map_snapshot_fname,$(mapid)))

ffmpeg-vid-to-snapshot=ffmpeg -y -i $(1) -vf "color=color=blue:size=336x40[blue];[in]crop=w=336:x=0[cropped];[cropped][blue]overlay[out]" -ss $(if $(3),$(3),00:04:00) -vframes 1 $(2)

# A function recipe to crop a snapshot image from map video
define make_snapshot_png
$(call map_snapshot_fname,$(1)): $(lastword $(wildcard ./exp-results/$(2)/videos/[0-9]*.mp4))
	$(call ffmpeg-vid-to-snapshot,$$<,$$@)

endef

# Mapping generated by
# cut -d, -f 1,11 exp-results/Random_Goal_Random_Spawn_Static_Maze.csv 
$(eval $(call make_snapshot_png,0127,2017_10_06_20_02_11-train_3D_4actions_blind-none_0001))
$(eval $(call make_snapshot_png,0169,2017_10_06_20_02_14-train_3D_4actions_blind-none_0001))
$(eval $(call make_snapshot_png,0246,2017_10_09_18_06_53-train_3D_4actions_blind-none_0001))
$(eval $(call make_snapshot_png,0336,2017_10_06_20_02_17-train_3D_4actions_blind-none_0001))
$(eval $(call make_snapshot_png,0445,2017_10_06_20_02_19-train_3D_4actions_blind-none_0001))
$(eval $(call make_snapshot_png,0589,2017_10_06_20_02_21-train_3D_4actions_blind-none_0001))
$(eval $(call make_snapshot_png,0691,2017_10_06_20_02_23-train_3D_4actions_blind-none_0001))
$(eval $(call make_snapshot_png,0828,2017_10_06_20_02_25-train_3D_4actions_blind-none_0001))
$(eval $(call make_snapshot_png,0844,2017_10_06_20_02_26-train_3D_4actions_blind-none_0001))
$(eval $(call make_snapshot_png,0956,2017_10_06_20_02_28-train_3D_4actions_blind-none_0001))


./exp-results/planning-09x09-0004.png: $(lastword $(wildcard ./exp-results/planning-09x09-0004/videos/*.mp4))
	$(call ffmpeg-vid-to-snapshot,$<,$@,00:00:00)

./exp-results/planning-09x09-0006.png: $(lastword $(wildcard ./exp-results/planning-09x09-0006/videos/*.mp4))
	$(call ffmpeg-vid-to-snapshot,$<,$@,00:00:00)
